export const store = [
    {
        id: "MA01",
        imageBig: "./imgs/minkaAireFan01.jpg",
        imageSmall: "./imgs/minkaAireFanS01.jpg",
        title: "Minka-Aire F736L-BS/SDBK Gear 54\" Inch Ceiling Fan with Integrated 18W LED Light and DC Motor in Brushed Steel/Sand Black Finish",
        rating: 4,
        reviews: 5,
        price: 499.95,
        listPrice: null,
        color: "Brushed Steel/Sand Black",
        brand: "MINKA-AIRE",
        LxWxH: "56 x 54 x 16 inches",
        material: "Material: Other",
        controllerType: "Remote Control",
        finishType: "",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "MA02",
        imageBig: "./imgs/minkaAireFan02.jpg",
        imageSmall: "./imgs/minkaAireFanS02.jpg",
        title: "Minka Aire F868L-BN Sleek 60\" Ceiling Fan with LED Light and Remote Control, Brushed Nickel",
        rating: 4.5,
        reviews: 6,
        price: 299.95,
        listPrice: null,
        color: "Black",
        brand: "MINKA-AIRE",
        LxWxH: "",
        material: "Wood",
        controllerType: "Remote Control",
        finishType: "Brushed",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "MA03",
        imageBig: "./imgs/minkaAireFan03.jpg",
        imageSmall: "./imgs/minkaAireFanS03.jpg",
        title: "Minka-Aire F467L-BNW Concept III 54\" Hugger with LED Lights, Brushed Nickel",
        rating: 0,
        reviews: 0,
        price: 359.95,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "MA04",
        imageBig: "./imgs/minkaAireFan04.jpg",
        imageSmall: "./imgs/minkaAireFanS04.jpg",
        title: "Minka-Aire F864L-BNK Barn 65 Ceiling Fan with LED Light and DC Motor in Burnished Nickel Finish",
        rating: 5,
        reviews: 1,
        price: 449.95,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "CM01",
        imageBig: "./imgs/craftmadeFan01.jpg",
        imageSmall: "./imgs/craftmadeFanS01.jpg",
        title: "Craftmade Kids Ceiling Fan Boys WB348TS Tiger Shark Warplane With Light, 48-Inch 3 Blade Hugger Ceiling Fan",
        rating: 5,
        reviews: 10,
        price: 265.20,
        listPrice: 302.00,
        color: "Tiger Shark",
        brand: "Craftmade",
        LxWxH: "48 x 48 x 17 inches",
        material: "Metal, Glass",
        controllerType: "Button Control",
        finishType: "",
        youSave: 36.80,
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "CM02",
        imageBig: "./imgs/craftmadeFan02.jpg",
        imageSmall: "./imgs/craftmadeFanS02.jpg",
        title: "Craftmade Rustic Ceiling Fan with Light and Remote WIN56ABZWP5 Winton, Aged Bronze, Weathered Pine Blades",
        rating: 4.5,
        reviews: 3,
        price: 212.48,
        listPrice: null,
        color: "Aged Bronze / Weathered Pine",
        brand: "Craftmade",
        LxWxH: "26.78 x 11.45 x 11.14 inches",
        material: "Metal, Glass",
        controllerType: "Button Control",
        finishType: "",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "CM03",
        imageBig: "./imgs/craftmadeFan03.jpg",
        imageSmall: "./imgs/craftmadeFanS03.jpg",
        title: "Craftmade K11291 Mobi 60\" Outdoor Ceiling Fan with 17 Watts LED Light Kit and Remote, 3 ABS Blades, Oiled Light Bronze",
        rating: 0,
        reviews: 0,
        price: 311.95,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "CM04",
        imageBig: "./imgs/craftmadeFan04.jpg",
        imageSmall: "./imgs/craftmadeFanS04.jpg",
        title: "Craftmade Outdoor Ceiling Fan with CFL Light PAR52AGV4 Port Arbor 4 Blade 52 Inch Wet for Patio, Galvanized",
        rating: 4,
        reviews: 1,
        price: 253.30,
        listPrice: 298.00,
        bestSeller: false,
        sale: true,
        new: false,
    },
    {
        id: "KL01",
        imageBig: "./imgs/kichlerFan01.jpg",
        imageSmall: "./imgs/kichlerFanS01.jpg",
        title: "Kichler 300230NI, Ceiling Fan Brushed Nickel 15\" Ceiling Fan with Light & Remote Control",
        rating: 4.5,
        reviews: 5,
        price: 399.00,
        listPrice: null,
        color: "Brushed Nickel",
        brand: "Kichler",
        LxWxH: "1 x 11.75 x 21 inches",
        material: "Metal, Glass",
        controllerType: "",
        finishType: "Finished",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "KL02",
        imageBig: "./imgs/kichlerFan02.jpg",
        imageSmall: "./imgs/kichlerFanS02.jpg",
        title: "Kichler 300265DBK Gentry 65\" Ceiling Fan with LED Lights and Wall Control, Distressed Black",
        rating: 5,
        reviews: 12,
        price: 850.00,
        listPrice: null,
        color: "Distressed Black",
        brand: "Kichler",
        LxWxH: "65 x 65 x 17 inches",
        material: "Steel",
        controllerType: "",
        finishType: "Finished",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "KL03",
        imageBig: "./imgs/kichlerFan03.jpg",
        imageSmall: "./imgs/kichlerFanS03.jpg",
        title: "Kichler 300209SBK, Ceiling Fan Satin Black 52\" Ceiling Fan with Light & Remote Control",
        rating: 5,
        reviews: 3,
        price: 599.95,
        listPrice: null,
        color: "Satin Black",
        brand: "Kichler",
        LxWxH: "1 x 52 x 15 inches",
        material: "Steel",
        controllerType: "Remote Control",
        finishType: "",
        youSave: "",
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "KL04",
        imageBig: "./imgs/kichlerFan04.jpg",
        imageSmall: "./imgs/kichlerFanS04.jpg",
        title: "Kichler 300103NI, Canfield Brushed Nickel 30\" Outdoor Ceiling Fan",
        rating: 3.5,
        reviews: 1,
        price: 165.75,
        listPrice: 174.95,
        bestSeller: false,
        sale: true,
        new: false,
    },
    {
        id: "MC01",
        imageBig: "./imgs/monteCarloFan01.jpg",
        imageSmall: "./imgs/monteCarloFanS01.jpg",
        title: "Monte Carlo 3MAVR60BSKOAD Maverick Modern Energy Star 60\" Ceiling Fan with LED Light and Hand Remote Control, 3 Balsa Wood Blades, Brushed Steel",
        rating: 5,
        reviews: 8,
        price: 855.96,
        listPrice: null,
        color: "Brushed Steel-koa Blades",
        brand: "Monte Carlo",
        LxWxH: "60 x 60 x 14 inches",
        material: "Metal",
        controllerType: "Remote Control",
        finishType: "",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "MC02",
        imageBig: "./imgs/monteCarloFan02.jpg",
        imageSmall: "./imgs/monteCarloFanS02.jpg",
        title: "Monte Carlo Fans 14PRR72AGPD Prairie Grand Windmill Energy Star 72\" Outdoor Ceiling Fan with LED Light and Hand Remote Control, 14 Wood Blades, Aged Pewter-Light Grey Weathered Oak Blades",
        rating: 4.5,
        reviews: 2,
        price: 1199.96,
        listPrice: null,
        color: "Aged Pewter-light Grey Weathered Oak Blades",
        brand: "Monte Carlo",
        LxWxH: "72 x 72 x 14 inches",
        material: "Metal",
        controllerType: "Remote Control",
        finishType: "",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "MC03",
        imageBig: "./imgs/monteCarloFan03.jpg",
        imageSmall: "./imgs/monteCarloFanS03.jpg",
        title: "Monte Carlo 5CY60BK Cyclone Energy Star 60\" Outdoor Ceiling Fan, 5 Blades, Matte Black",
        rating: 4.5,
        reviews: 1,
        price: 399.96,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "MC04",
        imageBig: "./imgs/monteCarloFan04.jpg",
        imageSmall: "./imgs/monteCarloFanS04.jpg",
        title: "Monte Carlo 3AMR60AGPD Armstrong Unique Energy Star 60\" Ceiling Fan with LED Light and Remote, 3 ABS Blades, Aged Pewter",
        rating: 5,
        reviews: 2,
        price: 669.96,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "C01",
        imageBig: "./imgs/casablancaFan01.jpg",
        imageSmall: "./imgs/casablancaFanS01.jpg",
        title: "Casablanca Indoor Ceiling Fan, with wall control - Panama 54 inch, Brushed Nickel, 55067",
        rating: 4,
        reviews: 4,
        price: 399.99,
        listPrice: null,
        color: "Brushed Nickel",
        brand: "Casablanca",
        LxWxH: "54 x 54 x 10.98 inches",
        material: "Material: Other",
        controllerType: "",
        finishType: "Finished",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "C02",
        imageBig: "./imgs/casablancaFan02.jpg",
        imageSmall: "./imgs/casablancaFanS02.jpg",
        title: "Casablanca Indoor Ceiling Fan with LED Light and remote control - Wisp 44 inch, Nobel Bronze, 59287",
        rating: 0,
        reviews: 0,
        price: 279.99,
        listPrice: null,
        color: "Noble Bronze",
        brand: "Casablanca",
        LxWxH: "44 x 44 x 12.08 inches",
        material: "Material: Plastic",
        controllerType: "Remote Control",
        finishType: "",
        youSave: "",
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "C03",
        imageBig: "./imgs/casablancaFan03.jpg",
        imageSmall: "./imgs/casablancaFanS03.jpg",
        title: "Casablanca Fan Company 59167 Casablanca Perseus Indoor/Outdoor Ceiling Fan with LED Light and Wall Control, Large, Brushed Nickel",
        rating: 0,
        reviews: 0,
        price: 599.99,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "C04",
        imageBig: "./imgs/casablancaFan04.jpg",
        imageSmall: "./imgs/casablancaFanS04.jpg",
        title: "Casablanca Heathridge Indoor / Outdoor Ceiling Fan with Pull Chain Control",
        rating: 4.5,
        reviews: 5,
        price: 549.99,
        listPrice: null,
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "QR01",
        imageBig: "./imgs/quorumFan01.jpg",
        imageSmall: "./imgs/quorumFanS01.jpg",
        title: "Quorum 196015-69 60\" Windmill Ceiling Fan in Noir with Weathered Oak Finished Blades, Damp Rated",
        rating: 5,
        reviews: 11,
        price: 1138.00,
        listPrice: null,
        color: "Noir",
        brand: "Quorum International",
        LxWxH: "",
        material: "Metal",
        controllerType: "Remote Control",
        finishType: "",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "QR02",
        imageBig: "./imgs/quorumFan02.jpg",
        imageSmall: "./imgs/quorumFanS02.jpg",
        title: "Quorum 3525-86 Protruding Mount, 5 Weathered Oak Blades Ceiling fan with 14 watts light, Oiled Bronze",
        rating: 4,
        reviews: 3,
        price: 382.00,
        listPrice: null,
        color: "Oiled Bronze",
        brand: "Quorum International",
        LxWxH: "52 x 52 x 18.46 inches",
        material: "Metal, Glass",
        controllerType: "",
        finishType: "Finished",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "QR03",
        imageBig: "./imgs/quorumFan03.jpg",
        imageSmall: "./imgs/quorumFanS03.jpg",
        title: "Quorum 96015-86 Indoor Windmill Ceiling Fan in Oiled Bronze with Weathered Oak Blades",
        rating: 4.5,
        reviews: 1,
        price: 1018.00,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "QR04",
        imageBig: "./imgs/quorumFan04.jpg",
        imageSmall: "./imgs/quorumFanS04.jpg",
        title: "Quorum 78605-30 Protruding Mount, 5 Medium Oak Blades Ceiling fan, Vintage Gold Leaf",
        rating: 3,
        reviews: 1,
        price: 350.00,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "LK01",
        imageBig: "./imgs/laskoFan01.jpg",
        imageSmall: "./imgs/laskoFanS01.jpg",
        title: "Lasko Portable Electric 42\" Oscillating Tower Fan with Fresh Air Ionizer, Timer and Remote Control for Indoor, Bedroom and Home Office Use, Silver 2551",
        rating: 4.5,
        reviews: 6,
        price: 102.00,
        listPrice: null,
        color: "Silver 2551",
        brand: "Lasko",
        LxWxH: "13 x 13 x 42.5 inches",
        material: "",
        controllerType: "Electronic controls",
        finishType: "Matte",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "LK02",
        imageBig: "./imgs/laskoFan02.jpg",
        imageSmall: "./imgs/laskoFanS02.jpg",
        title: "Lasko 2535 52″ Space-Saving Pedestal Tower Fan with Remote Control - Features Built-in Timer and Wide Spread Oscillation",
        rating: 5,
        reviews: 8,
        price: 59.99,
        listPrice: null,
        color: "Silver Gray",
        brand: "Lasko",
        LxWxH: "14 x 14 x 52.7 inches",
        material: "Plastic",
        controllerType: "Electronic controls",
        finishType: "",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "LK03",
        imageBig: "./imgs/laskoFan03.jpg",
        imageSmall: "./imgs/laskoFanS03.jpg",
        title: "Lasko U35115 Electric Oscillating High Velocity Stand-Up Tower Fan with Timer and Remote Control for Indoor, Bedroom and Home Office Use, 35 Inch, Silver Black",
        rating: 5,
        reviews: 3,
        price: 84.99,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "LK04",
        imageBig: "./imgs/laskoFan04.jpg",
        imageSmall: "./imgs/laskoFanS04.jpg",
        title: "Lasko Wind Curve Electric Oscillating Tower Fan with Bluetooth Technology for Indoor, Bedroom and Home Office Use, 42\", Blackwood T42905",
        rating: 4.5,
        reviews: 2,
        price: 274.00,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "HW01",
        imageBig: "./imgs/honeywellFan01.jpg",
        imageSmall: "./imgs/honeywellFanS01.jpg",
        title: "Honeywell Fresh Breeze Tower Fan with Remote Control HYF048 Black With Programmable Thermostat, Timer Shut-Off Function & Dust Filter",
        rating: 4.5,
        reviews: 5,
        price: 69.99,
        listPrice: null,
        color: "Black",
        brand: "Honeywell",
        LxWxH: "8.4 x 10.9 x 33.1 inches",
        material: "Plastic",
        controllerType: "Remote Control",
        finishType: "Painted",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "HW02",
        imageBig: "./imgs/honeywellFan02.jpg",
        imageSmall: "./imgs/honeywellFanS02.jpg",
        title: "Honeywell Quiet Set Whole Room Tower Fan",
        rating: 4.5,
        reviews: 2,
        price: 64.99,
        listPrice: null,
        color: "Black",
        brand: "Honeywell",
        LxWxH: "10 x 8 x 32 inches",
        material: "Plastic",
        controllerType: "Remote Control",
        finishType: "",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "HW03",
        imageBig: "./imgs/honeywellFan03.jpg",
        imageSmall: "./imgs/honeywellFanS03.jpg",
        title: "Honeywell TurboForce Tower Fan, Black",
        rating: 4.5,
        reviews: 1,
        price: 79.99,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "HW04",
        imageBig: "./imgs/honeywellFan04.jpg",
        imageSmall: "./imgs/honeywellFanS04.jpg",
        title: "Honeywell QuietSet Whole Room Tower Fan-Black, HYF290B",
        rating: 5,
        reviews: 4,
        price: 61.45,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "V01",
        imageBig: "./imgs/vornadoFan01.jpg",
        imageSmall: "./imgs/vornadoFanS01.jpg",
        title: "Vornado OSCR37 Tower Fan and Air Circulator with Remote, Smooth Oscillation, Timer and Touch Controls, 37\"",
        rating: 4.5,
        reviews: 3,
        price: 109.99,
        listPrice: null,
        color: "Black",
        brand: "Vornado",
        LxWxH: "12 x 12 x 36.8 inches",
        material: "Plastic",
        controllerType: "Remote Control",
        finishType: "",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "V02",
        imageBig: "./imgs/vornadoFan02.jpg",
        imageSmall: "./imgs/vornadoFanS02.jpg",
        title: "Vornado NGT335 Air Circulator Tower Fan with Remote Control and Versa-Flow, 33\", NGT335-33, Black",
        rating: 4.5,
        reviews: 6,
        price: 99.99,
        listPrice: null,
        color: "Black",
        brand: "Vornado",
        LxWxH: "11 x 11 x 32.3 inches",
        material: "Plastic",
        controllerType: "Touchpad Control",
        finishType: "",
        youSave: "",
        bestSeller: true,
        sale: false,
        new: false,
    },
    {
        id: "V03",
        imageBig: "./imgs/vornadoFan03.jpg",
        imageSmall: "./imgs/vornadoFanS03.jpg",
        title: "Vornado 173 Whole Room Tower Air Circulator Fan, 37\"",
        rating: 4,
        reviews: 1,
        price: 79.99,
        listPrice: 109.99,
        bestSeller: false,
        sale: true,
        new: false,
    },
    {
        id: "V04",
        imageBig: "./imgs/vornadoFan04.jpg",
        imageSmall: "./imgs/vornadoFanS04.jpg",
        title: "Vornado 143 Whole Room Air Circulator Tower Fan, 29\"",
        rating: 4,
        reviews: 2,
        price: 54.99,
        listPrice: 59.99,
        bestSeller: false,
        sale: true,
        new: false,
    },
    {
        id: "M01",
        imageBig: "./imgs/mistingFan01.jpg",
        imageSmall: "./imgs/mistingFanS01.jpg",
        title: "O2COOL Deluxe Misting Fan, 1, Grey",
        rating: 5,
        reviews: 3,
        price: 9.99,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "M02",
        imageBig: "./imgs/mistingFan02.jpg",
        imageSmall: "./imgs/mistingFanS02.jpg",
        title: "Lasko 7050 Misto Outdoor Misting Fan - Features Cooling Misters, Ideal for Camping, Patios, Picnics, & more",
        rating: 4.5,
        reviews: 1,
        price: 230.00,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "M03",
        imageBig: "./imgs/mistingFan03.jpg",
        imageSmall: "./imgs/mistingFanS03.jpg",
        title: "O2COOL 2 Pack Deluxe Misting Handheld Portable Misting Fan, Raspberry",
        rating: 3,
        reviews: 4,
        price: 18.26,
        listPrice: 21.49,
        bestSeller: false,
        sale: true,
        new: false,
    },
    {
        id: "M04",
        imageBig: "./imgs/mistingFan04.jpg",
        imageSmall: "./imgs/mistingFanS04.jpg",
        title: "HandFan Portable Handheld Misting Fan with 55ml Water Tank Rechargeable Personal Cooling Fan Mister Humidifier USB/Battery Operated Water Spray Mist Fan 180° Foldable 3 Speeds Strong Wind for Make-up Travel Outdoors Car Disney Land",
        rating: 3.5,
        reviews: 2,
        price: 19.99,
        listPrice: 25.99,
        bestSeller: false,
        sale: true,
        new: false,
    },
    {
        id: "E01",
        imageBig: "./imgs/exhaustFan01.jpg",
        imageSmall: "./imgs/exhaustFanS01.jpg",
        title: "Broan-NuTone 505 Exhaust Fan, White Vertical Discharge Ceiling Ventilation Fan, 8.5 Sones, 200 CFM, 8\"",
        rating: 4,
        reviews: 1,
        price: 59.99,
        listPrice: 111.35,
        bestSeller: false,
        sale: true,
        new: false,
    },
    {
        id: "E02",
        imageBig: "./imgs/exhaustFan02.jpg",
        imageSmall: "./imgs/exhaustFanS02.jpg",
        title: "Broan-NuTone AE110LK Flex Bathroom Exhaust Ventilation Fan with LED Light, Energy Star Certified, 110 CFM, 1.0 Sones, White",
        rating: 4.5,
        reviews: 2,
        price: 129.00,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
    {
        id: "E03",
        imageBig: "./imgs/exhaustFan03.jpg",
        imageSmall: "./imgs/exhaustFanS03.jpg",
        title: "iLIVING ILG8SF20V Wall Mounted Exhaust Fan, 20\" - Variable, Silver",
        rating: 4,
        reviews: 1,
        price: 200.00,
        listPrice: 249.99,
        bestSeller: false,
        sale: true,
        new: false,
    },
    {
        id: "E04",
        imageBig: "./imgs/exhaustFan04.jpg",
        imageSmall: "./imgs/exhaustFanS04.jpg",
        title: "HG POWER Through-the-Wall Ventilation Fan High CFM 6 Inch Exhaust Fan Extractor Blower Exhaust Attic Garage Kitchen Bathroom Ventilation Fan Ceiling and Wall Mount Exhaust Fan (308 CFM)",
        rating: 4.5,
        reviews: 2,
        price: 52.99,
        listPrice: null,
        bestSeller: false,
        sale: false,
        new: true,
    },
]